"""Level 2 updates

Revision ID: c2558b79b000
Revises: 6f1da75398f6
Create Date: 2026-05-20 00:28:57.241404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2558b79b000'
down_revision: Union[str, Sequence[str], None] = '6f1da75398f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('system_prompt', sa.String(), nullable=True))
    op.add_column('usage_logs', sa.Column('model_used', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'webhook_url')
    op.drop_column('users', 'plan_tier')
    op.drop_column('usage_logs', 'model_used')
    op.drop_column('api_keys', 'system_prompt')
    # ### end Alembic commands ###
